language: node_js

node_js:
- "8"

script:
- npm install
- npm test

notifications:
  email:
    recipients:
      - roger.urscheler@atos.net
      - richard.fazzio@atos.net
    on_success: never # default: change
    on_failure: always # default: always
    
webhooks:
    urls:
      - https://beta.circuit.com/rest/v2/webhooks/incoming/742bde9c-6a73-42aa-9bda-28c3eb78981d
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   never # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
