language: node_js

node_js:
- "8"

script:
- npm install
- npm test

notifications:
  email:
    recipients:
      - roger.urscheler@atos.net
      - richard.fazzio@atos.net
    on_success: never # default: change
    on_failure: always # default: always
    
webhooks:
    urls:
      - https://beta.circuit.com/rest/v2/webhooks/incoming/20930210-39be-4b89-a9d7-eb941b5b5e2f
      - https://beta.circuit.com/rest/v2/webhooks/incoming/127298e2-0569-46f7-9c20-7eea1e3adcd6
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   never # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
